### ISSUE TITLE
Functio remove.background doesn't use parameter ambientRNAprofile

### ISSUE THREAD

**Issue by mxposed** [LungCellAtlas/FastCAR#1]
If I don't have a variable `ambientProfile` declared outside of function, then the call
`correctedMatrix <- remove.background(cellMatrix, background)` fails:

```
Error in remove.background(cellMatrix, background) : 
  object 'ambientProfile' not found
```

**Comment by MarijnBerg** [comment]
Hi Nikolay, thank you for bringing that to my attention, it's been fixed now.
